# Group Organization
Managing the Organization resource

<!-- include(create-organization.apib) -->
<!-- include(get-organization.apib) -->
<!-- include(update-profile.apib) -->
<!-- include(update-design.apib) -->
<!-- include(update-system-donor-questions.apib) -->
<!-- include(mark-setup-complete.apib) -->
<!-- include(account-update.apib) -->
<!-- include(get-admins.apib) -->
<!-- include(get-account-users.apib) -->
