## Get Organization [/organization/{id}]

+ Parameters

    + id: `123` (required, integer) - The organization ID

### Get Organization [GET]
Get the attributes for the given organization

:::note
Controller Method: Api\Organization\OrganizationController@show
:::

+ Response 200 (application/json)

    + Attributes (Organization)
