## Mark Account Setup complete [/organization/{id}/setup-complete]

+ Parameters

    + id: `123` (required, integer) - The organization ID

### Mark Setup Complete [PUT]
This marks the organization to setup complete.

:::note
Controller Method: Api\Organization\OrganizationsController@setupComplete
:::

+ Request (application/json)

    + Attributes


+ Response 200 (application/json)
