## Delete Donor Question [/organization/{orgId}/donor-question/{dqId}]

+ Parameters

    + orgId: `123` (required, integer) - The organization ID
    + dqId: `12` (required, integer) - The donor question ID

### Delete Donor Question [DELETE]
Delete donor questions for the given organization

:::note
Controller Method: Api\DonorQuestion\DonorQuestionsController@destroy
:::

+ Response 200 (application/json)

