## Get Donor Question List [/organization/{orgId}/donor-question]

+ Parameters

    + orgId: `123` (required, integer) - The organization ID

### Get List [GET]
Get the list of all donor questions for the given organization

:::note
Controller Method: Api\DonorQuestion\DonorQuestionsController@index
:::

+ Response 200 (application/json)

    + Attributes (DonorQuestionList)
