## Get Recent Donors [/organization/{orgID}/recent-donors]

+ Parameters

    + orgID: `123` (required, integer) - The organization ID

### Get Recent Donors [GET]
Get the recent donors of the Organization

:::note
Donor\DonorsController@recentDonors
:::

+ Response 200 (application/json)

    + Attributes (Donation)