## Get Top Donors [/organization/{orgID}/recent-donors]

+ Parameters

    + orgID: `123` (required, integer) - The organization ID

### Get Top Donors [GET]
Get the top donors of the Organization's campaigns

:::note
Donor\DonorsController@topDonors
:::

+ Response 200 (application/json)

    + Attributes (Donation)