## Get Currencies List [/currencies]

### Get Currencies List [GET]
Get the list of all all currencies in the system

:::note
Controller Method: Api\CurrenciesController@index
:::

+ Response 200 (application/json)

    + Attributes (array)
        + (Currency)
