# Data Structures

<!-- include(user.apib) -->
<!-- include(organization.apib) -->
<!-- include(country.apib) -->
<!-- include(country-list.apib) -->
<!-- include(currency.apib) -->
<!-- include(donor-question.apib) -->
<!-- include(donor-question-list.apib) -->
<!-- include(campaign-reward.apib) -->
<!-- include(connected-account.apib) -->
<!-- include(campaign.apib) -->
<!-- include(campaign-detail.apib) -->
<!-- include(payouts.apib) -->
<!-- include(organization-admin-list.apib) -->
<!-- include(invitation.apib) -->
<!-- include(invitation-detail.apib) -->
<!-- include(user-detail.apib) -->
<!-- include(donation.apib) -->
