## Campaign

+ id: 1 (number) - Unique id of the campaign
+ organization_id: 1 (number) - Organization Id
+ name: `Help Age Ng` (string) - Name of th campaign
+ slug: `help_age_ng` (string) - Unique URL of the campaign
+ fundraising_goal: `25000` (number) - Fundraising goal
+ end_date: `2019-06-23` (string) - End date of the campaign
+ image: `abc.jpg` (string) - Full path of the image
+ payout_connected_account_id: `1` (number) - Connected number
