## CampaignReward

+ id: 1 (number) - Unique id of the reward
+ organization: `Signup` (string) - Name of the organization
+ campaign: `Go green` (string) - Name of the campaign
+ title: `Reard 3`(string) - Title of the clause
+ description: `description of test reward` (string) -  Description about the reward
+ min_amount: `230` (number) - Minimum amount
+ quantity: `540` (number) - Quantity
+ quantity_rewarded: `null`
+ image: `organizations\/1\/Xur5tlH9lIgtKqKuoEPwY7L6Pnq6gbZFzglCFXEu.jpeg` (string) - URL to the image or null
+ image_filename: `bottle.jpg` (string) - Original filename of the image
+ image_filesize: `28449` (number) - size of the image
