## CampaignDetail

+ id: 1 (number) - Unique id of the campaign
+ organization (Organization) - Organization Id
+ createdBy (User) - User Id
+ name: `Help Age Ng` (string) - Name of th campaign
+ slug: `help_age_ng` (string) - Unique URL of the campaign
+ fundraising_goal: `25000` (number) - Fundraising goal
+ funds_raised: `25000` (number) - Fundraising raised
+ end_date: `2019-06-23` (string) - End date of the campaign
+ image: `abc.jpg` (string) - Full path of the image
+ image_filename: `IMG_0702.JPG` - Image original name
+ video_url: `https://youtube.com/kitty-party` (string) - Video Url
+ description: `message` (string) - Campaign description
+ donor_message: `text` (string) - Donor message
+ payout_method: `check` (string) - Possible value bank, check, null
+ payout_connected_account (ConnectedAccount) - Organization connect account
+ payout_name: `Kim` (string) - Payout name
+ payout_address1: `Ambar Apartment` (string) - Address
+ payout_address2: `Tilak Nagar` (string) - Address
+ payout_city: `CA` (string) - Payout city name
+ payout_state: `CA` (string) - Payout state name
+ payout_zipcode: `90210` (string) - Payout zipcode
+ payout_country (Country) - Payout name
+ payout_payable_to: `John` (string) - Payout payable to
+ payout_schedule: `monthly` (string) - Posible values monthly, daily, completion
+ sort_order: `1` (number) - Sort order
+ published_at: `2019-06-22` (string) - Published date
+ publishedBy (User)
