## ConnectedAccount

+ account_id: 1 (number) - Unique id of the object
+ account_nickname: `Awesome Organization` (string) - Title of the clause
+ is_default: true (boolean) - Status flag of the account
+ campaigns (Campaign) (object)