## Donation
+ id: 2 (number)
+ organization (Organization) (object)
+ campaign_id: 1 (number) - Campaign Id
+ donor: `Doe` (string)
+ currency_id: 1 (number) - Currency Id
+ gross_amount: `campaign-admin` (string)
+ net_amount: `pFsFfZChK2` (string)
+ card_name: `2019-07-15 13:23:15` (string)
+ card_brand: ``
+ card_last_four: ``
+ payout_method: ``
+ mailing_address1: ``
+ mailing_address2: ``
+ mailing_city: ``
+ mailing_state: ``
+ mailing_zipcode: ``
+ billing_address1: ``
+ billing_address2: ``
+ billing_address2: ``
+ billing_state: ``
+ billing_zipcode: ``
+ created_at: `2019-07-15 13:23:15` (string)
+ campaign (Campaign) (object) 
+ currency (Currency) (object) 
+ reward: ``
