## Invitation
+ id: 2 (number)
+ organization_id: 1 (number)
+ first_name: `John` (string)
+ last_name: `Doe` (string)
+ email: `john.doe@gmail.com` (string)
+ role: `campaign-admin` (string)
+ code: `pFsFfZChK2` (string)
+ expires_at: `2019-07-15 13:23:15` (string)
