## InvitationDetail
+ id: 2 (number)
+ organization (Organization)
+ campaigns (array[Campaign])
+ invitee (User)
+ user (User)
+ first_name: `John` (string)
+ last_name: `Doe` (string)
+ email: `john.doe@gmail.com` (string)
+ role: `campaign-admin` (string)
+ code: `pFsFfZChK2` (string)
+ accepted_at: `2019-07-09 07:55:23` (string)
+ expires_at: `2019-07-15 13:23:15` (string)
