## Organization
+ id: 1 (number) - Unique id of the object
+ name: `Awesome Organization` (string) - Title of the clause
+ slug: `awesome-organization` (string) - Unique URL of the organization
+ address1: `Suite 52` (string)
+ address2: `Street address` (string)
+ city: `Los Angeles` (string)
+ state: `CA` (string)
+ zipcode: `90210` (string)
+ phone: `9876543210` (string)
+ country (Country)
+ currency (Currency)
+ owner (User)
+ cover_image: `https://lmn.cloudfront.net/xyz.jpg` (string) - URL to the image or null
+ logo: `https://lmn.cloudfront.net/xyz.jpg` (string) - URL to the image or null
+ appeal_photo: `https://lmn.cloudfront.net/xyz.jpg` (string) - URL to the image or null
+ primary_color: `fff000` (string)
+ secondary_color: `ff66dd` (string)
+ appeal_headline: `Please donate for the cause` (string)
+ appeal_message: `So we have this campaign for children. Would be lovely if you can donate.` (string)
+ system_donor_questions: `{"comment":{"enabled":false,"required":true},"mailing_address":{"enabled":true,"required":false}}` (string) - JSON with system question statuses
