## Payouts

+ account_id: 1 (number) - Unique id of the campaign
+ account_nickname: `abc` (string) - Nickname of the account
+ is_default: true (boolean) - status flag of of the account
+ campaigns (Campaign) (object) 
