FORMAT: 1A
HOST: https://rocketjar_v2.test/api/v1

# RocketJar API

<!-- include(data-structures/_data-structures.apib) -->

<!-- include(apis/organization/_organization-group.apib) -->
<!-- include(apis/donor-question/_donor-question-group.apib) -->
<!-- include(apis/campaign/_campaign-group.apib) -->
<!-- include(apis/invitation/_invitation-group.apib) -->
<!-- include(apis/miscellaneous/_misc.apib) -->
<!-- include(apis/user/_user.apib) -->
<!-- include(apis/donation/_donation-group.apib) -->
