## Change Password [/user/{user}/change-password]

+ Parameters

    + user: `1` (required, integer) - The user ID

### Change Password [PUT]
Change Password

:::note
Controller Method: Api\UsersController@changePassword
:::

+ Request (application/json)

    + Attributes

        + old_password: `Donald2019` (string, required) - Old Password
        + password: `Abcd123$` (string, required) - 8+ chars password with at least 1 capital letter, 1 number, 1 small letter and 1 special char
        + password_confirmation: `Abcd123$` (string, required) - Should match password.

+ Response 200 (application/json)

    + Attributes (User)
