# Group Campaign
Managing the Campaign resource

<!-- include(create-campaign.apib) -->
<!-- include(update-campaign.apib) -->
<!-- include(get-campaign.apib) -->
<!-- include(create-campaign-reward.apib) -->
<!-- include(get-rewards.apib) -->
<!-- include(show-reward.apib) -->
<!-- include(update-reward.apib) -->
<!-- include(delete-reward.apib) -->
<!-- include(get-payouts.apib) -->
<!-- include(update-donor-message.apib) -->
<!-- include(update-payout.apib) -->
<!-- include(get-campaign-admins.apib) -->