## Delete Reward [/organization/{orgID}/campaign/{campID}/reward/{reward}]

+ Parameters

    + orgID: `123` (required, integer) - The organization ID
    + campID : `123` (required, integer) - The campaign ID
    + reward: `123` (required, integer) - The reward ID

### Delete Reward [DELETE]
Delete a particular reward

:::note
Campaign\RewardsController@destroy
:::

+ Response 200 (application/json)
