## Get Payouts [/organization/{organization}/get-payouts]

+ Parameters

    + organization: `123` (required, integer) - The organization ID

### Get Payouts [GET]
Get the payouts of an given Organization

:::note
Campaign\PayoutsController@index
:::

+ Response 200 (application/json)

    + Attributes (Payouts)