## Get Rewards [/organization/{orgID}/campaign/{camID}/reward]

+ Parameters

    + orgID: `123` (required, integer) - The organization ID
    + camID : `123` (required, integer) - The campaign ID

### Get Rewards [GET]
Get the rewards of an given Campaign

:::note
Campaign\RewardsController@index
:::

+ Response 200 (application/json)

    + Attributes (CampaignReward)