## Get Campaign [/organization/{organization}/campaign/{campaign}]

+ Parameters

    + organization: `123` (required, integer) - The organization ID
    + campaign : `1` (required, integer) - The campaign ID

### Get Campaign [GET]
Get the campaign for given organization

:::note
Campaign\CampaignsController@show
:::

+ Response 200 (application/json)

    + Attributes (CampaignDetail)
