## Show Reward [/organization/{organization}/campaign/{campaign}/reward/{reward}]

+ Parameters

    + organization: `123` (required, integer) - The organization ID
    + campaign : `123` (required, integer) - The campaign ID
    + reward: `123` (required, integer) - The reward ID

### Show Reward [GET]
Get a particular reward

:::note
Campaign\RewardsController@show
:::

+ Response 200 (application/json)

    + Attributes (CampaignReward)