## Update Payout [/organization/{organization}/campaign/{campaign}/payout]

+ Parameters

    + organization: `123` (required, integer) - The organization ID
    + campaign: `1` (required, integer) - The campaign ID

### Update payout [PUT]
Update payout for the given organization campaign

:::note
Controller Method: Api\Campaign\Campaign\CampaignsController@update
:::

+ Request (application/json)

    + Attributes

        + payout_method: `check` (string)
        + payout_connected_id: `1` (number) - Requird if payout_method is bank
        + payout_name: `kim` (string) - Payout name
        + payout_address1: `Ambar Apartment` (string) -
        + payout_address2: `Tilak Nagar` (string, optional) - Address
        + payout_city: `CA` (string) - Payout city name
        + payout_state: `CA` (string) - Payout state name
        + payout_zipcode: `90210` (string) - Payout zipcode
        + payout_country_id: `1` (number) - Payout country id
        + payout_payable_to: `John` (string) - Payout payable to
        + payout_organization_name: `SSC High School` (string)  - Payout organization Name
        + payout_schedule: `monthly` (string, required) - Posible values monthly, daily, completion

+ Response 200 (application/json)

    + Attributes (CampaignDetail)
